/*
 * This software is available under Apache License
 * Copyright (c) 2020
 */

apply plugin: "application"

dependencies {
    implementation project(":${rootProject.name}-desktop")
    implementation project(":${rootProject.name}-ext-ecs");
    implementation project(":${rootProject.name}-ext-ecs-extra");
    implementation project(":${rootProject.name}-ext-decs");
    implementation project(":${rootProject.name}-ext-tween");
    implementation project(":${rootProject.name}-ext-network");
}

application {
    mainClass.set('org.pixel.demo.learning.canvas.CanvasGradientDemo')
    if (org.gradle.internal.os.OperatingSystem.current().isMacOsX()) {
        applicationDefaultJvmArgs = ["-XstartOnFirstThread"]
    }
}
