/*
 * This software is available under Apache License
 * Copyright (c) 2020
 */

// main project settings:
rootProject.name = "pixel"

// functions:
def getAndroidSdkPath() {
    if (System.getenv("ANDROID_HOME") != null) {
        return System.getenv("ANDROID_HOME");
    }

    def localProperties = new File(rootDir, "local.properties")
    if (localProperties.exists()) {
        def properties = new Properties()
        localProperties.withInputStream { stream ->
            properties.load(stream)
        }

        if (properties.getProperty("sdk.dir")) {
            return properties.getProperty("sdk.dir");
        }
    }

    return null;
}

// vars:
var androidSdk = getAndroidSdkPath()
print("Android SDK: " + androidSdk)

// modules:
include "modules/commons",
        "modules/math",
        "modules/graphics",
        "modules/content",
        "modules/core",
        "modules/pipeline",
        "modules/blueprint"

// platform modules:
include "platform/desktop"
if (androidSdk != null) {
    include "platform/android"
}

// extensions:
include "extensions/ext-log4j2",
        "extensions/ext-ecs",
        "extensions/ext-ecs-extra",
        "extensions/ext-tween",
        "extensions/ext-network"

// tools:
include "tools/arkade"

// demos:
if (System.properties["PIXEL_RELEASE"] == null) {
    // desktop:
    include "demos/desktop/demo-desktop-learning",
            "demos/desktop/demo-desktop-concept",
            "demos/desktop/demo-desktop-imgui"

    // android:
    if (androidSdk != null) {
        include "demos/android/demo-android-learning"
    }
}

// bootstrap module names:
rootProject.children.each(({
    def parts = it.name.split("/")
    def prefix = rootProject.name + "-"
    it.name = prefix + parts.last()
} as Closure))
