# -----------------------------------------------------------------------
# ARKADE server properties
# -----------------------------------------------------------------------
# This is the configuration file for the ARKADE server.
# It contains various settings that control the behavior of the server.
# You can modify these settings to customize the server to your needs.
# Please refer to the documentation for more information on each setting.
# -----------------------------------------------------------------------

# -----------------------------------------------------------------------
# General properties
# -----------------------------------------------------------------------
# Server name
general.serverName=ARKADE
# Server version
general.serverVersion=1.0.0

# -----------------------------------------------------------------------
# Network properties
# -----------------------------------------------------------------------
# Server binding address
network.bindingAddress=0.0.0.0
# Server binding port
network.bindingPort=10000
# Max connections
network.maxConnections=100
# Force SSL
network.forceSSL=false
# Network processing threads
network.threads=10

