apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Add the classpath for the Android Gradle Plugin here
        // Make sure to use a version compatible with your Gradle version
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

android {
    namespace "org.pixel.android"

    compileSdk 36

    defaultConfig {
        minSdkVersion 30

        versionCode 1
        versionName rootProject.version

        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation project(":${rootProject.name}-android")
    implementation project(":${rootProject.name}-ext-tween")

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.16.0'
}