plugins {
    id 'java-library'
}

group = rootProject.group
version = rootProject.version

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    // Flux core
    api project(':pixel-ext-flux')
    
    // Desktop platform (for Mouse/Keyboard access)
    api project(':pixel-desktop')
    
    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}
